GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###

GET  http://localhost:8080/api/poets/queryPoet/1
Accept: application/json

###
# @no-cookie-jar
GET http://localhost:8080/api/poets/1

###

# curl -X POST http://localhost:8080/api/poets/add -H "Content-Type: application/json" -d '{
#  "name": "李白",
#  "birthDate": "701-02-08",
#  "deathDate": "762-11-30",
#  "dynasty": "唐",
#  "biography": "李白，字太白，号青莲居士，又号‘谪仙人’..."
#}'
POST http://localhost:8080/api/poets/add
Content-Type: application/json

{
  "name": "李白2",
  "birthDate": "701-02-08",
  "deathDate": "762-11-30",
  "dynasty": "唐",
  "biography": "李白，字太白，号青莲居士，又号‘谪仙人’..."
}

###
# curl -X POST http://localhost:9001/ssm/poets2/create -H "Content-Type: application/x-www-form-urlencoded" -d "id=1&name=李白&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介"
POST http://localhost:9001/ssm/poets2/create
Content-Type: application/x-www-form-urlencoded

id=1&name=李白&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介

###


# curl -X POST http://localhost:9001/ssm/poets2/create -H "Content-Type: application/x-www-form-urlencoded" -d "id=1&name=李白&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介"
POST http://localhost:9001/ssm/poets2/create
Content-Type: application/x-www-form-urlencoded

name=李白2&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介

###


###
# curl -X POST http://localhost:9001/ssm/poets2/create -H "Content-Type: application/x-www-form-urlencoded" -d "id=1&name=李白&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介"
POST http://localhost:9001/ssm/poets2/create
Content-Type: application/x-www-form-urlencoded

name=李白244&birthDate=2024-11-27&deathDate=2024-12-01&dynasty=唐朝&biography=诗人简介



